### ISSUE TITLE
500 Error When claiming any item

### ISSUE THREAD

**Issue by jarstelfox** [kavdev/bidr_project#66]

**Comment by kavdev** [comment]
https://sentry.io/kavanaugh-development/bidr/issues/206466983/

**Comment by kavdev** [comment]
Has to do with the new updates to [django-polymorphic](https://github.com/django-polymorphic/django-polymorphic) and the fact that the way we wrote that line of code is dumb

**Comment by kavdev** [comment]
Should be a fix for this particular bug:

```python
def claim_item(request, slug, auction_id):
    item_id = request.POST["item_id"]
    bid_id = request.POST["bid_id"]

    auction_instance = Auction.objects.get(id=auction_id)
    bid_instance = Bid.objects.get(id=bid_id)

    try:
        item_collection_instance = auction_instance.bidables.instance_of(ItemCollection).get(id=item_id)
    except ItemCollection.DoesNotExist:
        pass
    else:
        item_collection_instance.claim(bid_instance)
```

This ``instance_of`` replacement will need to be implemented all over the app lol

**Comment by kavdev** [comment]
lol who the hell wrote ``claim_item``

**Comment by kavdev** [comment]
best part is view tests would have caught this bug :)
